[project]
name = "c-env"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "clang>=21.1.7",
    "libclang>=18.1.1",
    "networkx>=3.6.1",
    "ollama>=0.6.1",
    "openai>=2.15.0",
    "openpyxl>=3.1.5",
    "pick>=2.6.0",
    "plotly>=6.6.0",
    "pydantic>=2.12.5",
    "pygments>=2.19.2",
    "pyvis>=0.3.2",
    "requests>=2.32.5",
    "rich>=14.3.2",
    "setuptools>=82.0.0",
    "streamlit>=1.54.0",
    "tiktoken>=0.12.0",
    "tree-sitter-custom[core]",
]

[tool.uv.workspace]
members = [
    "tree-sitter-c",
]

[tool.uv.sources]
tree-sitter-custom = { workspace = true }

[dependency-groups]
dev = [
    "black>=26.3.1",
    "isort>=8.0.1",
]
